name: deploy-first-service
on: 
  push: 
    branches:
      - 'main'
    paths:
      - 'services/first-service/**'



jobs: 
  test: 
    runs-on: ubuntu-latest
    env:
      working-directory: 'services/first-service'
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: yarn install
      - name: Unit tests
        working-directory: ${{env.working-directory}}
        run: yarn unit
      - name: Deploy
        working-directory: ${{env.working-directory}}
        run: yarn deploy
        
