name: First Service - Deploy Prod

on: 
  push:
    branches:
      - 'main'
    paths:
      - 'services/first-service/**'




jobs: 
  test:
    needs: check
    if: needs.check.outputs.run_job == 'true'
    runs-on: ubuntu-latest
    env:
      working-directory: 'services/first-service'
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: yarn install
      - name: Unit tests
        working-directory: ${{env.working-directory}}
        run: yarn unit

  deploy-to-prod:
    needs: test
    environment: Production
    runs-on: ubuntu-latest
    env:
      working-directory: 'services/first-service'
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: yarn install
      - name: Deploy
        working-directory: ${{env.working-directory}}
        run: STAGE=prod yarn deploy