name: Second Service - Deploy Prod

on: 
  release:
    types: [published]
    paths:
      - 'services/second-service/**'




jobs:
  test:
    
    runs-on: ubuntu-latest
    env:
      working-directory: 'services/second-service'
    steps: 
      - name: Wait For Check
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          checkName: Create Release
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: yarn install
      - name: Unit tests
        working-directory: ${{env.working-directory}}
        run: yarn unit

  deploy-to-prod:
    needs: test
    environment: Production
    runs-on: ubuntu-latest
    env:
      working-directory: 'services/second-service'
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: yarn install
      - name: Deploy
        working-directory: ${{env.working-directory}}
        run: STAGE=prod yarn deploy