name: Second Service - Deploy Devint01

on: 
  push:
    branches: 
      - 'integration'
    paths:
      - 'services/second-service/**'




jobs: 
  test: 
    runs-on: ubuntu-latest
    env:
      working-directory: 'services/second-service'
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: yarn install
      - name: Unit tests
        working-directory: ${{env.working-directory}}
        run: yarn unit
      - name: Deploy
        working-directory: ${{env.working-directory}}
        run: yarn deploy
        
  deploy-to-devint:
    needs: test
    runs-on: ubuntu-latest
    env:
      working-directory: 'services/second-service'
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set stage to dev
        run: export STAGE=dev
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: yarn install
      - name: Deploy
        working-directory: ${{env.working-directory}}
        run: yarn deploy